### ISSUE TITLE
Add block timestamp to Indexer

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack-indexer#250]
Umar is helping create week-over-week product reporting to feed into this spreadsheet: https://docs.google.com/spreadsheets/d/1Rc2pQbJ-xgPusviuTGc_zjd2YWH-TPGEKzq9Q2jHnow/edit#gid=0

Currently, we only have blockNumber in the indexer to use for time. The reporting will be much easier if we're able to add blockTimestamp.

Could we complete this by 9/10 (when Umar is available to work on the report?)

**Comment by bard** [comment]
@meglister in what API calls (well, JSON files) specifically would timestamp be required?

**Comment by ufkhan97** [comment]
Ideally, everywhere there is a blockNumber there should also be a blockTimestamp but here specifically are the ones that would help w this reporting: 

rounds.json

- createdAtBlock
- (updatedAtBlock)

Applications.json (/ projects.json)

- createdAtBlock
- statusUpdatedAtBlock 

votes.json
- blockNumber

**Comment by gravityblast** [comment]
hey @meglister @ufkhan97 !
adding the timestamp will require us to make 1 RPC call for each event we receive, which will slow down a lot the initial chain catch up. 
The best way is to keep only the block number in the indexer, and to call `eth_getBlock` from other indexer client and apps to get the timestamp

**Comment by gravityblast** [comment]
would it be doable for you @ufkhan97

**Comment by ufkhan97** [comment]
I wonder if there's a way to make this easier/faster way to add. Having human-readable time data is critical for all reporting and could be an unlock for what gets displayed on the front-end 

Some compromises can be made as well like we may not need it to be granular to the second -- to the minute may be close enough for 90% of use cases. 

If RPC calls are a pain point we could try using a DB which provides the block_number and block_time for many blocks at once. For example, this dune query: https://dune.com/queries/2964310

Wdyt @gravityblast ?

**Comment by bard** [comment]
@ufkhan97 @gravityblast @meglister it's unlikely for this to be done by 9/10 (if we mean Sep 9), sorry. As you can see by the issue tracker, there is plenty to fix on the operational side before we can add to the functional one.
