### ISSUE TITLE
replace JSON files with Postgres database

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack-indexer#314]
We're storing the data in JSON files, as the data gets larger this is becoming more of a bottleneck to write to, it is also difficult to query, making it hard to support more advanced features in Grants Stack, like the new homepage.

I suggest we use https://kysely.dev/ as a database abstraction.

**Comment by vacekj** [comment]
"Awesome, hell yeah, perfect, let's go" :shipit:
