### ISSUE TITLE
migrate allo-indexer-client to this repo

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack-indexer#317]
The allo indexer client is a Typescript wrapper for the Indexer API: https://github.com/gitcoinco/allo-indexer-client

It is living in a another repo at the moment, which makes it difficult when working on Grants Stack because you have to make changes in three different repos (Indexer, Indexer Client, Grants Stack)

**Comment by vacekj** [comment]
Good things that I think are achievable short-term without changing architecture:
- have a single source of types that we use everywhere - most likely this should be the Indexer, since that's the source of the data.
- Have both the frontends and the indexer-client import these types.
- These types can be zod schemas, so that we kill two birds with one stone - parsing and typing, and they're always in sync - this is super important for the types to be actually useful and provide safety instead of just autocomplete.

**Comment by bard** [comment]
This would be a good time to address the question of what the client is actually adding. If not much (and not enough to justify the indirection) there may be better ways of investing the effort.

**Comment by boudra** [comment]
I see a benefit of having the types for the API available to be imported from other Typescript projects, which is one of the things that repo is doing, but this can be done directly from this repository without the need to have another package.

As per the actual wrapping fetching logic I think that code could be in Grants Stack.

**Comment by bard** [comment]
> I see a benefit of having the types for the API available to be imported from other Typescript projects, which is one of the things that repo is doing, but this can be done directly from this repository without the need to have another package, and if those exported types could also be a zod schema then even better.

I agree.

> For the actual client code that wraps the API, we have to find what works for us, do we see value from having a client that anyone can install and use to build apps from, not just Grants Stack?

The enabler there would be a public API, of which a client is one of the possible incarnations. IMHO a better trade-off would be swagger spec — less work on our side, just as much if not more clarity for users, plus clients in several languages can be generated from it if one so desires.

**Comment by boudra** [comment]
> The enabler there would be a public API, of which a client is one of the possible incarnations. IMHO a better trade-off would be swagger spec — less work on our side, just as much if not more clarity for users, plus clients in several languages can be generated from it if one so desires.

You reminded me of this project I saw a while ago: https://openapistack.co/

I haven't used it or looked too deep into it but we could do a little spike to see how it works. We would get server + client types tRPC style, and like you said, have a transparent HTTP API, while also allowing other languages to have clients for it.

**Comment by bard** [comment]
Haven't used this either but it popped on my radar a while ago: https://github.com/asteasolutions/zod-to-openapi

**Comment by boudra** [comment]
> Haven't used this either but it popped on my radar a while ago: https://github.com/asteasolutions/zod-to-openapi

This looks way simpler and less magical than openapistack, love it 👍

**Comment by boudra** [comment]
How does this sound as a plan of action:

1. Implement current data schema (votes, contributions, prices etc.) as Zod types in this repository
2. Update Grants Stack to get those types from here as a Git NPM package instead of `allo-indexer-client`
3. Replace the client with a thin abstraction in Grants Stack, was thinking something like:

```ts
interface AlloIndexer {
    getRoundById(id: string): Promise<Round>;
}
```

with an implementation calling `fetch` and `zod` validating responses.

5. Use https://github.com/asteasolutions/zod-to-openapi when we implement the API: https://github.com/gitcoinco/allo-indexer/issues/173

**Comment by vacekj** [comment]
sounds good @boudra

**Comment by boudra** [comment]
closing this because it is superseded by the work on the grant stack data client: https://github.com/gitcoinco/grants-stack/tree/main/packages/grants-stack-data-client
