### ISSUE TITLE
run calculator operations in subprocess

### ISSUE THREAD

**Issue by bard** [gitcoinco/grants-stack-indexer#352]

**Comment by boudra** [comment]
@bard out of curiosity is this an actual operating system subprocess or a node worker thread?

**Comment by bard** [comment]
I'm planning to use [fork](https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options) to get both a true subprocess and an easier IPC than with `spawn`, but open to ideas.

**Comment by boudra** [comment]
> I'm planning to use [fork](https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options) to get both a true subprocess and an easier IPC than with `spawn`, but open to ideas.

It makes sense to me, I asked because was curious about [worker threads](https://nodejs.org/api/worker_threads.html#worker-threads), they are advertised as a solution to do CPU intensive work, but I saw somewhere that they're not actual os threads, I have only used `child_process` for this kind of work so not sure what are the trade offs.

**Comment by boudra** [comment]
@owocki we ended up using a Node.js worker pool and heavy caching which did great for GG19: https://github.com/gitcoinco/grants-stack-indexer/pull/364

but I can see this becoming non scalable if we introduce more complex QF algorithms, it would make sense to put calcs on a separate server as a queue consumer of sorts

another idea was to bring back what cgrants did for estimates, correct me if I am wrong but I believe that it calculated potential matches based on a $1 / $100 / $1000 donations and then interpolate to give an estimate, at the moment we're literally calculating matches without the donations and with donations and then showing the difference in the front end
