### ISSUE TITLE
use the new avalanche scorer for rounds on Avalanche

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack-indexer#519]
* we already download the default scorer data. download the Avalanche scorer data too
* update how we save scores: change the key in the db to be `#{scorer}-#{address}`
* update the calculations and matching estimates to use
  * the avalanche scores for rounds running on Avalanche
  * the default scorer for all the other rounds

**Comment by michellema1208** [comment]
@gravityblast thanks so much for this! Just to confirm: does this cover everything Umar needs from Grants Stack in order to do post-round calculations? Or is that something separate?

**Comment by michellema1208** [comment]
@gravityblast I'm also going to move this over to the TODO board, given we don't have IPM next week. Lmk if you want to review it with the team first though!

**Comment by gravityblast** [comment]
hey @michellema1208 !
this is needed only for linear QF calculations, and not used for cluster matching

**Comment by michellema1208** [comment]
Closing as complete
